'use client';

import { useMemo } from 'react';
import { SandpackProvider, SandpackPreview } from '@codesandbox/sandpack-react';
import type { BuilderFiles } from '@/types/code';

interface CodePreviewProps {
    files: BuilderFiles;
    reloadKey?: number;
}

const DEFAULT_TAILWIND_CONFIG = `
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}
`;

const DEFAULT_POSTCSS_CONFIG = `
module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}
`;

const DEFAULT_GLOBALS_CSS = `
@tailwind base;
@tailwind components;
@tailwind utilities;

body {
  font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
}
`;

const DEFAULT_LAYOUT = `
import './globals.css'

export const metadata = {
  title: 'Next.js Sandbox',
  description: 'Generated by SouvikAI',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
`;

export function CodePreview({ files, reloadKey = 0 }: CodePreviewProps) {
    const sandpackFiles = useMemo(() => {
        const result: Record<string, string> = {
            '/tailwind.config.js': DEFAULT_TAILWIND_CONFIG,
            '/postcss.config.js': DEFAULT_POSTCSS_CONFIG,
            '/app/globals.css': DEFAULT_GLOBALS_CSS,
            '/app/layout.tsx': DEFAULT_LAYOUT,
        };
        for (const [path, content] of Object.entries(files)) {
            result[`/${path}`] = content;
        }
        return result;
    }, [files]);

    return (
        <div className="flex-1 min-h-0 bg-background" key={reloadKey}>
            <SandpackProvider
                template="nextjs"
                files={sandpackFiles}
                customSetup={{
                    dependencies: {
                        'lucide-react': 'latest',
                        'framer-motion': 'latest',
                        'clsx': 'latest',
                        'tailwind-merge': 'latest',
                        'tailwindcss': 'latest',
                        'postcss': 'latest',
                        'autoprefixer': 'latest',
                        '@radix-ui/react-icons': 'latest',
                        '@radix-ui/react-slot': 'latest',
                    },
                }}
            >
                <div className="h-full w-full [&_.sp-layout]:h-full [&_.sp-layout]:w-full [&_.sp-preview]:h-full [&_.sp-preview-iframe]:h-full [&_.sp-preview-iframe]:w-full">
                    <SandpackPreview
                        showOpenInCodeSandbox={false}
                        showRefreshButton={false}
                    />
                </div>
            </SandpackProvider>
        </div>
    );
}
