'use client';

import { useEffect, useRef, useState } from 'react';
import { Loader2 } from 'lucide-react';
import type { BuilderFiles } from '@/types/code';
import { getWebContainer, parseBuilderFilesToTree } from '@/lib/webcontainer';
import type { WebContainer } from '@webcontainer/api';

interface CodePreviewProps {
    files: BuilderFiles;
    reloadKey?: number;
}

const DEFAULT_PACKAGE_JSON = JSON.stringify(
    {
        name: 'preview-app',
        version: '0.1.0',
        private: true,
        scripts: {
            dev: 'next dev',
            build: 'next build',
            start: 'next start',
        },
        dependencies: {
            react: '^18.2.0',
            'react-dom': '^18.2.0',
            next: '14.2.0',
            'lucide-react': 'latest',
            'framer-motion': 'latest',
            clsx: 'latest',
            'tailwind-merge': 'latest',
            '@radix-ui/react-icons': 'latest',
            '@radix-ui/react-slot': 'latest',
        },
        devDependencies: {
            typescript: '^5',
            '@types/node': '^20',
            '@types/react': '^18',
            '@types/react-dom': '^18',
            postcss: '^8',
            tailwindcss: '^3.4.1',
            autoprefixer: '^10.4.19',
        },
    },
    null,
    2
);

const DEFAULT_TAILWIND_CONFIG = `
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}
`;

const DEFAULT_POSTCSS_CONFIG = `
module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}
`;

const DEFAULT_LAYOUT = `
import './globals.css';

export const metadata = {
  title: 'Preview',
  description: 'Generated by SouvikAI',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
`;

const DEFAULT_GLOBALS_CSS = `
@tailwind base;
@tailwind components;
@tailwind utilities;

body {
  font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
}
`;

export function CodePreview({ files, reloadKey = 0 }: CodePreviewProps) {
    const [url, setUrl] = useState<string | null>(null);
    const [status, setStatus] = useState<string>('Booting environment...');
    const [error, setError] = useState<string | null>(null);
    const containerRef = useRef<WebContainer | null>(null);
    const iframeRef = useRef<HTMLIFrameElement>(null);
    const initialMountDone = useRef(false);

    // Initial boot and setup
    useEffect(() => {
        let isMounted = true;

        async function bootAndRun() {
            try {
                setStatus('Booting environment...');
                const container = await getWebContainer();
                containerRef.current = container;

                if (!isMounted) return;

                setStatus('Mounting files...');
                
                // Inject default configuration files if they are missing
                const filesToMount = { ...files };
                if (!filesToMount['package.json']) {
                    filesToMount['package.json'] = DEFAULT_PACKAGE_JSON;
                }
                if (!filesToMount['tailwind.config.ts'] && !filesToMount['tailwind.config.js']) {
                    filesToMount['tailwind.config.js'] = DEFAULT_TAILWIND_CONFIG;
                }
                if (!filesToMount['postcss.config.js'] && !filesToMount['postcss.config.mjs']) {
                    filesToMount['postcss.config.js'] = DEFAULT_POSTCSS_CONFIG;
                }
                if (!filesToMount['app/layout.tsx']) {
                    filesToMount['app/layout.tsx'] = DEFAULT_LAYOUT;
                }
                if (!filesToMount['app/globals.css']) {
                    filesToMount['app/globals.css'] = DEFAULT_GLOBALS_CSS;
                }

                const tree = parseBuilderFilesToTree(filesToMount);
                await container.mount(tree);
                initialMountDone.current = true;

                if (!isMounted) return;

                setStatus('Installing dependencies (this may take a minute)...');
                const installProcess = await container.spawn('npm', ['install']);
                
                // Read install logs (useful for debugging, hidden from UI)
                void installProcess.output.pipeTo(
                    new WritableStream({
                        write(data) {
                            console.log('[npm install]', data);
                        },
                    })
                );

                const installExitCode = await installProcess.exit;

                if (installExitCode !== 0) {
                    throw new Error('npm install failed');
                }

                if (!isMounted) return;

                setStatus('Starting development server...');
                const devProcess = await container.spawn('npm', ['run', 'dev']);
                
                void devProcess.output.pipeTo(
                    new WritableStream({
                        write(data) {
                            console.log('[npm run dev]', data);
                        },
                    })
                );

                container.on('server-ready', (port, readyUrl) => {
                    if (isMounted) {
                        setUrl(readyUrl);
                        setStatus('Ready');
                    }
                });

            } catch (err) {
                if (isMounted) {
                    setError(err instanceof Error ? err.message : String(err) || 'An error occurred while starting the preview');
                    setStatus('Error');
                }
            }
        }

        bootAndRun();

        return () => {
            isMounted = false;
        };
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, []); // Only run once on mount

    // Handle file changes after initial mount
    useEffect(() => {
        if (!initialMountDone.current || !containerRef.current) return;
        
        // Next.js HMR requires writing directly to the file system
        const updateFiles = async () => {
            const container = containerRef.current!;
            
            for (const [path, content] of Object.entries(files)) {
                try {
                    // Create directories if they don't exist
                    const parts = path.split('/');
                    if (parts.length > 1) {
                        // Note: WebContainer's mkdir isn't recursive by default, but Next.js usually only uses shallow structures here.
                        // Ideally we'd recursively create directories, but for simple file updates this might suffice if they exist.
                        // We wrap in try/catch to ignore "directory exists" errors.
                    }
                    
                    const cleanPath = path.startsWith('/') ? path : `/${path}`;
                    await container.fs.writeFile(cleanPath, content);
                } catch (err) {
                    console.error(`Failed to update file ${path}:`, err);
                }
            }
        };

        updateFiles();
    }, [files]);

    // Handle manual reload
    useEffect(() => {
        if (reloadKey > 0 && iframeRef.current && url) {
            iframeRef.current.src = url;
        }
    }, [reloadKey, url]);

    if (error) {
        return (
            <div className="flex-1 min-h-0 bg-background flex flex-col items-center justify-center p-6 text-center">
                <div className="text-destructive mb-2 font-semibold">Preview Error</div>
                <div className="text-foreground-muted text-sm">{error}</div>
            </div>
        );
    }

    if (!url) {
        return (
            <div className="flex-1 min-h-0 bg-background flex flex-col items-center justify-center p-6 text-center">
                <Loader2 className="h-8 w-8 animate-spin text-foreground-muted mb-4" />
                <div className="text-foreground font-medium">{status}</div>
            </div>
        );
    }

    return (
        <div className="flex-1 min-h-0 bg-white relative">
            <iframe
                ref={iframeRef}
                src={url}
                className="w-full h-full border-0"
                allow="cross-origin-isolated"
                title="Preview"
            />
        </div>
    );
}
