/**
 * Builder (Forge) workspace types.
 *
 * The Builder is a code-generation agent: it reasons about a request, emits
 * milestones describing its plan, and applies file-system actions to a virtual
 * project. State is persisted in Supabase (`builder_workspaces`,
 * `builder_files`, `builder_messages`) so projects survive across sessions and
 * devices. The client mirrors that state in memory while editing.
 */

/** A virtual project file system: path → file contents. */
export type BuilderFiles = Record<string, string>;

/** A single mutation the agent performs on the virtual file system. */
export type BuilderFileAction =
    | { kind: 'create'; path: string; content: string }
    | { kind: 'edit'; path: string; content: string }
    | { kind: 'delete'; path: string }
    | { kind: 'rename'; from: string; to: string };

/**
 * A "step" rendered in the agent's vertical timeline. A step is either a
 * milestone label, a record of a file action that was just applied, or a
 * record of a tool call (currently only `read` — the agent fetched the full
 * contents of an existing file because the snapshot in the system prompt was
 * truncated).
 */
export type BuilderStep =
    | { id: string; kind: 'milestone'; text: string; status: 'doing' | 'done' }
    | { id: string; kind: 'action'; action: BuilderFileAction; status: 'done' }
    | { id: string; kind: 'read'; path: string; status: 'done' };

/**
 * A single proposed file change generated by the agent during one turn,
 * scoped to a single workspace path. Renames are decomposed into a paired
 * `delete` (at the original path) + `create` (at the new path) so the
 * review UI can display each side of the move with its own diff.
 */
export interface PendingChange {
    /** Path this change targets in the post-turn workspace. */
    path: string;
    kind: 'create' | 'edit' | 'delete';
    /** Content at turn-start (`null` if the file did not exist yet). */
    before: string | null;
    /** Content after the turn (`null` if the file was removed). */
    after: string | null;
    /**
     * If this change is one half of a rename, the linked partner path.
     * `renamedTo` is set on the deleted half; `renamedFrom` on the
     * created half. Used purely for UI labels.
     */
    renamedFrom?: string;
    renamedTo?: string;
}

/**
 * Review state attached to an assistant message that produced file
 * changes during its turn. Pending changes that have been accepted or
 * rejected are removed from `pending` (rejected changes are also rolled
 * back on disk via the workspace files API).
 */
export interface MessageReview {
    pending: PendingChange[];
    /**
     * Total number of changes the turn produced (pending + already
     * resolved). Used so the UI can show "3 of 5 reviewed" without
     * having to remember the original list.
     */
    total: number;
}

/** A single message in the builder conversation. */
export interface BuilderMessage {
    id: string;
    role: 'user' | 'assistant';
    /** User-visible prose. For assistant messages, this is the final summary. */
    content: string;
    /** Only populated for assistant messages. */
    steps?: BuilderStep[];
    /** True while the assistant is still streaming a response into this message. */
    isStreaming?: boolean;
    /** True if the request errored mid-stream. */
    errored?: boolean;
    /**
     * Diff-review state for this turn. Only populated on assistant
     * messages whose turn produced at least one file action. Populated
     * once the stream finishes.
     */
    review?: MessageReview;
    createdAt: number;
}

/** Server-streamed event shape (NDJSON). */
export type BuilderStreamEvent =
    | { type: 'milestone'; text: string }
    | { type: 'action'; action: BuilderFileAction }
    | { type: 'read'; path: string }
    | { type: 'text'; delta: string }
    | { type: 'error'; message: string }
    | { type: 'done' };

/** Persisted workspace loaded from Supabase. */
export interface BuilderWorkspace {
    id: string;
    title: string;
    files: BuilderFiles;
    messages: BuilderMessage[];
    activeFile: string | null;
    createdAt: number;
    updatedAt: number;
}

/** Lightweight summary used for listings (sidebar / workspaces page). */
export interface BuilderWorkspaceSummary {
    id: string;
    title: string;
    activeFile: string | null;
    createdAt: number;
    updatedAt: number;
}
